# Example of a playbook which includes a role
# Use roles to package up logic which could be used as a template for tasks that have a common purpose
# An example for a role would be to setup an nginx webserver, elasticsearch node, kafka node(cluster) etc.
---
- name: Setup Nginx on remote machine
  hosts: all
  become: true
  roles:
    - redis-setup
